array:
  baseline: 20.0
  bl_max: 100.0
  bl_min: 10.0
  diameter: 4.0
  quantum_eff: 0.6
  ratio: 6.0
  spec_res: 20.0
  t_efficiency: 0.8
  t_slew: 36000.0
  throughput: 0.15
  wl_max: 18.5
  wl_min: 4.0
  num_apertures: 4
  num_outputs: 2
  primary_temp: 48
  primary_emissivity: 0.025
  d_temp: 23
  pixel_size: 23e-6
  dc_per_pix: 1
  detector_wl_min: 5e-6
  detector_wl_max: 28e-6
  pix_per_wl: 2.2
  fixed_baseline: False
models:
  fov_taper: gaussian  # type of FoV taper, I recommend Gaussian
  localzodi: darwinsim  # localzodi model
optimization:
  N_pf: 25
  characterization: True
  experiments:
    Experiment_1:
      in_HZ: true
      radius_p_max: 1.5
      radius_p_min: 0.5
      sample_size: 50
      temp_s_max: 7310.0
      temp_s_min: 4370.0
  habitable: true
  limit:
    A: .inf
    F: .inf
    G: .inf
    K: .inf
    M: .inf
  limit_mode: experiments
  opt_limit: experiments
  opt_limit_factor: 0.9
  snr_target: 7
  snr_char: 44.1
  n_orbits: 5
  t_search: 78840000.0
other:
  fov_threshold: 0.01
  image_size: 100
  n_cpu: 8
  n_plugins: 5
  output_filename: none
  output_path: none
  wl_optimal: 15